### ISSUE TITLE
`gcolor` option not working on python3

### ISSUE THREAD

**Issue by gentimouton** [cosmologicon/pygame-text#1]
Hello, nice library!
Out of the box, all examples work perfectly on python 2.7.
However, on Python 3.6, using pygame 1.9.3, I get a `ValueError: operands could not be broadcast together with shapes (58,) (117,59) ` from line 315 (`                    array[:,:,j] = ((1.0 - m) * array[:,:,j] + m * gcolor[j]).astype(array.dtype)
`). 
This issue goes away if I remove the `gcolor` argument from the last example.
Cheers!

**Comment by cosmologicon** [comment]
Don't use surfarray anymore so hopefully this isn't an issue any longer.
