### ISSUE TITLE
Using gsub rules with pygame

### ISSUE THREAD

**Issue by rohitsaluja22** [cosmologicon/pygame-text#2]
Hi, Every font file comes with a gsub file which is a set of rules that define substituting consegutive glyphs with a joint glyph for example. Pygame ignores such gsub files while rendering font. Can you tell how to force pygame to use gsub rules?

When gsub rules are not used, in Devanagari "म्ह" looks like "म् ह"(ignore space) as shown in the image:-

![pygame2](https://user-images.githubusercontent.com/16031087/42432117-5ed7f37c-838c-11e8-8612-e3273f03cb7e.png)

**Comment by cosmologicon** [comment]
Good question. Is this a question about pygame or about pygame-text? This repository is for pygame-text which uses pygame, but it's not part of the pygame library. I should clarify that in the documentation.

If it's about pygame, I recommend asking through [one of the pygame help channels](https://www.pygame.org/wiki/info).

**Comment by illume** [comment]
@rohitsaluja22 There's a patch for SDL_ttf to use HarfBuzz which solves this apprently. https://bugzilla.libsdl.org/show_bug.cgi?id=3046

I suggest testing it out, and making your case on the bug tracker. Perhaps also asking on http://discourse.libsdl.org/

**Comment by illume** [comment]
pygame also has a freetype module which avoids SDL_ttf entirely.
https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.Font

Freetype mentions better Devanagari support post 2015. Do you know of a font I can use to try it?
the example/freetype_misc.py can probably be used to try it out.

I had to add the utf-8 coding line to the top, and I tried a couple of fonts with sysfont... but on my system none of them rendered at all (instead showing squares).
```python
# -*- coding: utf-8 -*-

    font = freetype.SysFont('helveticaneue', 32)

    font.render_to(screen, (32, 32), u"म्ह देवनागरी Hello World", colors["red"],
                   colors['grey_dark'], size=64)
```

src_c/freetype is where the code lives for freetype if you want to tweak it.

**Comment by illume** [comment]
Ok... I found a font here "Hind Light": https://www.1001fonts.com/devanagari-fonts.html

Here is a screenshot using pygame.freetype
<img width="469" alt="screen shot 2018-12-13 at 13 13 12" src="https://user-images.githubusercontent.com/9541/49938092-18122200-fed9-11e8-80ea-53b763fb461f.png">

I also found some system fonts with devanagari in the tile for feeding into SysFont:
```python
[x for x in pygame.freetype.get_fonts() if 'devanagari' in x]
```

It doesn't look like freetype uses the gsub rules, and that indeed... HarfBuzz is required.

**Comment by cosmologicon** [comment]
Thanks for responding. Hope that helped.
